core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('buyershop.urls')),
    path('account/', include('account.urls')),
    path('textile/', include('textilefactory.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

textilefactory/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('textile/', views.textile_order, name='textile')
]

textilefactory/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _


User = get_user_model()


class TextileOrderFile(models.Model):
    files = models.FileField(
        verbose_name=_('Файлы'),
        upload_to='media/files',
    )

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'


class TextileOrder(models.Model):
    name = models.CharField(
        max_length=128,
        verbose_name=_('Название швейного заказа')
    )
    description = models.CharField(
        max_length=1024,
        verbose_name=_('Описание заказа')
    )
    status = models.PositiveSmallIntegerField(
        choices=(
            (1, _('Обрабатывается')),
            (2, _('Выполнен')),
        ),
        default=1,
        verbose_name=_('Статус заказа')
    )
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='textile_orders',
        verbose_name=_('Пользователь'),
    )
    created_date = models.DateTimeField(
        verbose_name=_('Дата создания швейного заказа'),
        auto_now_add=True,
    )
    updated_date = models.DateTimeField(
        verbose_name=_('Дата изменения швейного заказа'),
        auto_now=True)
    is_active = models.BooleanField(
        verbose_name=_('Заказ активен'),
        default=True,
    )
    files = models.ForeignKey(TextileOrderFile, on_delete=models.CASCADE)

    def __str__(self):
        return f'Швейный заказ {self.user}'

    class Meta:
        verbose_name = 'Швейный заказ'
        verbose_name_plural = 'Швейные заказы'



textilefactory/forms.py
from django import forms
from .models import TextileOrder, TextileOrderFile


class TextileOrderForm(forms.ModelForm):
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), label='Файлы', required=False)

    class Meta:
        model = TextileOrder
        fields = ['name', 'description', 'files']
        enctype = 'multipart/form-data'

textilefactory/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import TextileOrderForm, TextileOrderFile
from .models import TextileOrder


def textile_order(request):
    user = request.user
    if request.method == "POST":
        if not request.user.is_authenticated:
            return redirect('register')

        form = TextileOrderForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = user

            for f in request.FILES.getlist('files', None):
                # проверяем, существует ли файл уже в базе данных
                file_instance = TextileOrderFile.objects.create(files=f)

            obj.files = file_instance
            obj.save()
            return redirect('index')
    form = TextileOrderForm()
    return render(request, template_name='textile.html', context={'form': form})

textilefactory/templates/textile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- ***** Ordering Area Starts ***** -->
    <section class="mt-5 pt-5">
        <div class="container py-5">
            <div class="row justify-content-center align-items-center">
                <div class="col-12">
                    <div class="card card-registration" style="border-radius: 15px;" >
                        <div class="card-body p-0">
                            <div class="p-5" style="background-color: #f0f0f0;">
                                <div class="text-center">
                                    <h1 class="fw-bold">Заказать шитье одежды</h1>
                                </div>
                                <hr class="my-4">
                                <form action="." method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="mb-3">
                                        <label for="id_name" class="form-label">Название швейного заказа:</label>
                                        <input type="text" name="name" maxlength="128" required="" class="form-control" id="id_name">
                                    </div>
                                    <div class="mb-3">
                                        <label for="id_description" class="form-label">Описание заказа:</label>
                                        <textarea name="description" maxlength="1024" required="" class="form-control" id="id_description" rows="5"></textarea>
                                    </div>
                                    <div class="mb-3">
                                        <label for="id_files" class="form-label">Выберите файлы:</label>
                                        <input type="file" name="files" multiple="" class="form-control" id="id_files">
                                    </div>
                                    <div class="text-center">
                                        <button class="btn btn-primary" type="submit">Отправить</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ***** Ordering Area Ends ***** -->



{% endblock content %}